apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-service-account
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: ecommerce-service-account
    app.kubernetes.io/part-of: ecommerce
    app.kubernetes.io/managed-by: Helm