apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ecommerce-allow-internal
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: ecommerce-network-policy
    app.kubernetes.io/part-of: ecommerce
    app.kubernetes.io/managed-by: Helm
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector: {}

  egress:
    - to:
        - podSelector: {}

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    - to:
        - ipBlock:
            cidr: 0.0.0.0/0