apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://github.com/Aosman4395/EKS-V2.git
    targetRevision: main
    path: platform-manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true