name: Build and Push Services to ECR

on:
  push:
    branches:
      - main
    paths:
      - "services/**"
      - ".github/workflows/build-and-push.yml"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: build-and-push-production
  cancel-in-progress: false

env:
  AWS_REGION: eu-west-2
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - api-gateway
          - dashboard-api
          - inventory-service
          - notification-service
          - order-service
          - payment-service
          - scheduler
          - shipping-service
          - worker

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::673588459289:role/github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6

      - name: Build, scan and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SERVICE_NAME: ${{ matrix.service }}
        run: |
          IMAGE_URI="$ECR_REGISTRY/$SERVICE_NAME:$IMAGE_TAG"

          docker build --no-cache --pull -t "$IMAGE_URI" "./services/$SERVICE_NAME"

          trivy image --severity HIGH,CRITICAL --exit-code 1 "$IMAGE_URI"

          docker push "$IMAGE_URI"